name: aime2024
output_dir: benchmark_results/3B-7B/aime/prefix/

dataset:
  name: HuggingFaceH4/aime_2024
  split: train


enable_prefix_aware_scheduling: true

# Generator model configuration (lower memory for offloading)
generator_model:
  model: "meta-llama/Llama-3.2-3B-Instruct"

  gpu_memory_utilization: 0.35
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

# Verifier model configuration (lower memory for offloading)
verifier_model:
  model: "peiyi9979/math-shepherd-mistral-7b-prm"

  gpu_memory_utilization: 0.6
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

search_config:
  approach: beam_search
  beam_width: 4
  n: 64
  num_iterations: 10

  temperature: 0.8
