name: aime2024
output_dir: benchmark_results/1.5B-1.5B/aime/vg_search/baseline/

dataset:
  name: HuggingFaceH4/aime_2024
  split: train

enable_spec_diff: false
offload_enabled: false

# Generator model configuration (lower memory for offloading)
generator_model:
  model: "Qwen/Qwen2.5-Math-1.5B-Instruct"

  gpu_memory_utilization: 0.20
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

# Verifier model configuration (lower memory for offloading)
verifier_model:
  model: "Skywork/Skywork-o1-Open-PRM-Qwen-2.5-1.5B"

  gpu_memory_utilization: 0.20
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

search_config:
  approach: vg_search
  beam_width: 4
  n: 8
  num_iterations: 10

  temperature: 0.8
