name: amc2023
output_dir: benchmark_results/1.5B-7B/amc/spec_prefix_no_future/

dataset:
  name: zwhe99/amc23
  split: test
  
enable_spec_diff: true
enable_prefix_aware_scheduling: true

# Generator model configuration (lower memory for offloading)
generator_model:
  model: "Qwen/Qwen2.5-Math-1.5B-Instruct"

  gpu_memory_utilization: 0.28
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

# Verifier model configuration (lower memory for offloading)
verifier_model:
  model: "peiyi9979/math-shepherd-mistral-7b-prm"

  gpu_memory_utilization: 0.62
  tensor_parallel_size: 1
  enable_prefix_caching: true
  seed: 42

search_config:
  approach: beam_search
  beam_width: 4
  n: 512
  num_iterations: 10

  temperature: 0.8
